# Try to find the Google NIFTY_INFUSION_EXTERNALS library and headers.
#  NIFTY_INFUSION_EXTERNALS_FOUND        - system has qpbo lib
#  NIFTY_INFUSION_EXTERNALS_INCLUDE_DIRS - the qpbo include directory
#  NIFTY_INFUSION_EXTERNALS_LIBRARIES    - libraries needed to use qpbo

# find_path(NIFTY_INFUSION_EXTERNALS_INCLUDE_DIR
#   qpbo/NIFTY_INFUSION_EXTERNALS.h

#     PATHS  ENV C_INCLUDE_PATH
#            ENV C_PLUS_INCLUDE_PATH
#            ENV INCLUDE_PATH

#     HINTS ENV C_INCLUDE_PATH
#           ENV C_PLUS_INCLUDE_PATH
#           ENV INCLUDE_PATH
# )

# find_library(NIFTY_INFUSION_EXTERNALS_LIBRARY
#   NAMES qpbo
#   DOC "The qpbo library"
#     PATHS ENV LIBRARY_PATH
#           ENV LD_LIBRARY_PATH
# )

# set(NIFTY_INFUSION_EXTERNALS_INCLUDE_DIRS ${NIFTY_INFUSION_EXTERNALS_INCLUDE_DIR})
# set(NIFTY_INFUSION_EXTERNALS_LIBRARIES    ${NIFTY_INFUSION_EXTERNALS_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(NIFTY_INFUSION_EXTERNALS
  FOUND_VAR 
    NIFTY_INFUSION_EXTERNALS_FOUND
  REQUIRED_VARS 
      # NIFTY_INFUSION_EXTERNALS_INCLUDE_DIR 
      # NIFTY_INFUSION_EXTERNALS_LIBRARY 
      # NIFTY_INFUSION_EXTERNALS_LIBRARIES
)

mark_as_advanced(NIFTY_INFUSION_EXTERNALS_FOUND)
