# Try to find the Google NIFTY_INFUSION_EXTERNALS library and headers.
#  NIFTY_INFUSION_EXTERNALS_FOUND        - system has qpbo lib
#  NIFTY_INFUSION_EXTERNALS_INCLUDE_DIRS - the qpbo include directory
#  NIFTY_INFUSION_EXTERNALS_LIBRARIES    - libraries needed to use qpbo


find_package(AD3 REQUIRED)
find_package(QPBO REQUIRED)


SET(NIFTY_INFUSION_EXTERNALS_LIBRARIES
    ${AD3_LIBRARY}
    ${QPBO_LIBRARY}
)
SET(NIFTY_INFUSION_EXTERNALS_INCLUDE_DIRS
    ${AD3_INCLUDE_DIRS}
    ${QPBO_INCLUDE_DIRS}
)


include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(NIFTY_INFUSION_EXTERNALS
    FOUND_VAR 
    NIFTY_INFUSION_EXTERNALS_FOUND
    #
    REQUIRED_VARS 
        NIFTY_INFUSION_EXTERNALS_INCLUDE_DIRS 
        NIFTY_INFUSION_EXTERNALS_LIBRARIES
)

mark_as_advanced(NIFTY_INFUSION_EXTERNALS_FOUND)
